from .nodes import (
    QlipAutoSparse,
    QlipCache,
    QlipCacheReport,
    QlipCompile,
    QlipDrafter,
    QlipEnginesLoader,
    QlipLoraStack,
    QlipLoraSwitch,
    QlipProgressive,
    QlipQuantConfig,
    QlipSpectrumFit,
    QlipTimerReport,
    QlipTimerStart,
    QlipTimerStop,
    QlipTokenPrune,
)

NODE_CLASS_MAPPINGS = {
    "QlipEnginesLoader": QlipEnginesLoader,
    "QlipLoraStack": QlipLoraStack,
    "QlipLoraSwitch": QlipLoraSwitch,
    "QlipTimerStart": QlipTimerStart,
    "QlipTimerStop": QlipTimerStop,
    "QlipTimerReport": QlipTimerReport,
    "QlipCache": QlipCache,
    "QlipCacheReport": QlipCacheReport,
    "QlipAutoSparse": QlipAutoSparse,
    "QlipProgressive": QlipProgressive,
    "QlipSpectrumFit": QlipSpectrumFit,
    "QlipCompile": QlipCompile,
    "QlipQuantConfig": QlipQuantConfig,
    "QlipDrafter": QlipDrafter,
    "QlipTokenPrune": QlipTokenPrune,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "QlipEnginesLoader": "Qlip Engines Loader",
    "QlipLoraStack": "Qlip LoRA Stack",
    "QlipLoraSwitch": "Qlip LoRA Switch",
    "QlipTimerStart": "Qlip Timer Start",
    "QlipTimerStop": "Qlip Timer Stop",
    "QlipTimerReport": "Qlip Timer Report",
    "QlipCache": "Qlip Cache",
    "QlipCacheReport": "Qlip Cache Report",
    "QlipAutoSparse": "Qlip Auto Sparse",
    "QlipProgressive": "Qlip Progressive",
    "QlipSpectrumFit": "Qlip Spectrum Fit",
    "QlipCompile": "Qlip Compile",
    "QlipQuantConfig": "Qlip Quant Config",
    "QlipDrafter": "Qlip Drafter",
    "QlipTokenPrune": "Qlip Token Prune",
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
